name: Auto Merge

on:
  workflow_call:
    secrets:
      REPO_ADMIN_TOKEN:
        required: false

jobs:
  auto-merge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    if: "!github.event.pull_request.draft"
    steps:
      - name: Enable auto-merge (squash)
        continue-on-error: true
        run: gh pr merge "$PR_URL" --auto --squash
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.REPO_ADMIN_TOKEN || secrets.GITHUB_TOKEN }}
